### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by rollerozxa** [principia-preservation-project/principia-web-forum#1]
- [x] Convert entire project to Twig
	- [x] Pages
		- [x] activeusers.php
		- [x] ~~editgroups.php~~ (removed)
		- [x] ~~editperms.php~~ (removed)
		- [x] editpost.php
		- [x] forum.php
		- [x] index.php
		- [x] manageforums.php
		- [x] memberlist.php
		- [x] newreply.php
		- [x] newthread.php
		- [x] private.php
		- [x] search.php
		- [x] sendprivate.php
		- [x] showprivate.php
		- [x] thread.php
	- [x] Remove unnecessary esc() functions.
	- [x] Remove old pageheader() and pagefooter() functions.
- [x] Replace current HTML+BBCode formatting combo to Markdown with specific tags added.
- [x] Go through all code for SQL vulns and whatnot.
- [x] Merge forum search with main principia-web search page.
- [x] Merge forum profile functionality with main principia-web profile functionality.
- [x] Merge userlink code.
- [x] Merge the forum and principia-web databases into one.
